# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rl_env_pb2 as rl__env__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rl_env_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RlEnvironmentStub(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObservationSpace = channel.unary_unary(
                '/rl_env.RlEnvironment/GetObservationSpace',
                request_serializer=rl__env__pb2.ObservationSpaceRequest.SerializeToString,
                response_deserializer=rl__env__pb2.ObservationSpace.FromString,
                _registered_method=True)
        self.GetActionSpace = channel.unary_unary(
                '/rl_env.RlEnvironment/GetActionSpace',
                request_serializer=rl__env__pb2.ActionSpaceRequest.SerializeToString,
                response_deserializer=rl__env__pb2.ActionSpace.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/rl_env.RlEnvironment/Reset',
                request_serializer=rl__env__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl__env__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/rl_env.RlEnvironment/Step',
                request_serializer=rl__env__pb2.StepRequest.SerializeToString,
                response_deserializer=rl__env__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/rl_env.RlEnvironment/Configure',
                request_serializer=rl__env__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=rl__env__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.SetLevel = channel.unary_unary(
                '/rl_env.RlEnvironment/SetLevel',
                request_serializer=rl__env__pb2.SetLevelRequest.SerializeToString,
                response_deserializer=rl__env__pb2.SetLevelResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/rl_env.RlEnvironment/StartTraining',
                request_serializer=rl__env__pb2.StartTrainingRequest.SerializeToString,
                response_deserializer=rl__env__pb2.StartTrainingResponse.FromString,
                _registered_method=True)
        self.EndTraining = channel.unary_unary(
                '/rl_env.RlEnvironment/EndTraining',
                request_serializer=rl__env__pb2.EndTrainingRequest.SerializeToString,
                response_deserializer=rl__env__pb2.EndTrainingResponse.FromString,
                _registered_method=True)


class RlEnvironmentServicer(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    def GetObservationSpace(self, request, context):
        """Environment info endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionSpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Core RL endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Configuration endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Training mode control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RlEnvironmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObservationSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObservationSpace,
                    request_deserializer=rl__env__pb2.ObservationSpaceRequest.FromString,
                    response_serializer=rl__env__pb2.ObservationSpace.SerializeToString,
            ),
            'GetActionSpace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionSpace,
                    request_deserializer=rl__env__pb2.ActionSpaceRequest.FromString,
                    response_serializer=rl__env__pb2.ActionSpace.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=rl__env__pb2.ResetRequest.FromString,
                    response_serializer=rl__env__pb2.ResetResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=rl__env__pb2.StepRequest.FromString,
                    response_serializer=rl__env__pb2.StepResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=rl__env__pb2.ConfigureRequest.FromString,
                    response_serializer=rl__env__pb2.ConfigureResponse.SerializeToString,
            ),
            'SetLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLevel,
                    request_deserializer=rl__env__pb2.SetLevelRequest.FromString,
                    response_serializer=rl__env__pb2.SetLevelResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=rl__env__pb2.StartTrainingRequest.FromString,
                    response_serializer=rl__env__pb2.StartTrainingResponse.SerializeToString,
            ),
            'EndTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.EndTraining,
                    request_deserializer=rl__env__pb2.EndTrainingRequest.FromString,
                    response_serializer=rl__env__pb2.EndTrainingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl_env.RlEnvironment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl_env.RlEnvironment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RlEnvironment(object):
    """============================================================================
    Service Definition
    ============================================================================

    """

    @staticmethod
    def GetObservationSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/GetObservationSpace',
            rl__env__pb2.ObservationSpaceRequest.SerializeToString,
            rl__env__pb2.ObservationSpace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActionSpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/GetActionSpace',
            rl__env__pb2.ActionSpaceRequest.SerializeToString,
            rl__env__pb2.ActionSpace.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/Reset',
            rl__env__pb2.ResetRequest.SerializeToString,
            rl__env__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/Step',
            rl__env__pb2.StepRequest.SerializeToString,
            rl__env__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/Configure',
            rl__env__pb2.ConfigureRequest.SerializeToString,
            rl__env__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/SetLevel',
            rl__env__pb2.SetLevelRequest.SerializeToString,
            rl__env__pb2.SetLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/StartTraining',
            rl__env__pb2.StartTrainingRequest.SerializeToString,
            rl__env__pb2.StartTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_env.RlEnvironment/EndTraining',
            rl__env__pb2.EndTrainingRequest.SerializeToString,
            rl__env__pb2.EndTrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
